In [34]:
import numpy as np
import matplotlib.pyplot as plt
import bellman as bl
import pm 

In [38]:
np.shape(pm.P@pm.v0)

(10, 5)

In [35]:
np.shape(pm.pi)

(10, 5)

In [3]:
pm.pi[0]

array([0.39037659, 0.04187614, 0.04774541, 0.46046324, 0.05953863])

In [4]:
np.dot(pm.pi[0],pm.pi[1])

0.21432525250554008

In [5]:
v = bl.sinf(pm.v0,pm)

In [6]:
np.shape(v)

(10,)

In [7]:
v[0]

-1.7969302085839733

In [8]:
v = bl.sap(pm.v0,pm)

In [9]:
np.shape(v)

(10,)

In [14]:
Q= bl.Qiter(pm.Q0,rect='s')

In [15]:
np.shape(Q)

(10, 5)

In [16]:
Q

array([[-1.62949766,  1.41645765,  1.12698905, -2.1774539 ,  1.40242107],
       [-0.4181785 ,  0.0495617 ,  1.26720217, -0.43949754, -0.65769374],
       [-0.69684306, -0.36367206,  0.63115083,  0.25978367,  0.5188345 ],
       [-0.07071851, -1.17467473,  3.43358241,  0.30665444,  1.86666076],
       [-0.3776812 , -0.76293577,  0.96779603,  0.23739906,  0.9399713 ],
       [ 1.28578221,  0.06557086, -0.77256925, -0.37668305, -0.99630589],
       [ 0.59918319,  0.0539933 , -1.97039422,  0.52104941, -1.43814708],
       [ 0.41642367, -0.85083273,  0.57129648, -1.02884549,  0.59032318],
       [ 0.12836589, -0.040765  ,  1.36607253,  1.48666469, -1.31993616],
       [-0.54810414, -0.76705947,  0.06406727, -0.98002243,  0.2508773 ]])

In [12]:
pm.S

10

In [13]:
bl.Kappa(pm.v0,p=1)

1.5398603477402473

In [18]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
np.tile([3,2],4)

array([3, 2, 3, 2, 3, 2, 3, 2])

In [23]:
np.reshape(np.outer([3,3],[2,4]),-1)

array([ 6, 12,  6, 12])

In [32]:
A = np.zeros((pm.A,pm.S*pm.A))
for i in range(pm.A):
    A[i,i*pm.S:(i+1)*pm.S]=1

In [33]:
A[-1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])